version: "3"

services:
  api:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    container_name: api
    depends_on:
      - postgres
      - mongo
      - redis
    ports:
      - '8080:8080'

  postgres:
    restart: always
    image: 'postgres:latest'
    networks:
      - backend
    container_name: postgres
    environment:
      - POSTGRES_DB=usersdb
      - POSTGRES_USER=reddit
      - POSTGRES_PASSWORD=reddit
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - './deploy/:/docker-entrypoint-initdb.d/'

  mongo:
    restart: always
    image: 'mongo:latest'
    networks:
      - backend
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=post
    ports:
      - '27017-27019:27017-27019'

  redis:
    restart: always
    image: 'redis:latest'
    networks:
      - backend
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge